services:
  backend:
    image: ${DOCKERHUB_USERNAME}/chatapp-backend:${IMAGE_TAG:-latest}
    container_name: backend
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}

  frontend:
    image: ${DOCKERHUB_USERNAME}/chatapp-frontend:${IMAGE_TAG-latest}
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
