- name: Restart Prometheus
  community.docker.docker_container:
    name: prometheus
    state: started
    restart: true

- name: Restart AlertManager
  community.docker.docker_container:
    name: alertmanager
    state: started
    restart: true