Vagrant.configure("2") do |config|

  # Máy ảo self-hosted runner (ví dụ web1)
  config.vm.define "self-hosted-runner" do |web1|
    web1.vm.box = "ubuntu/jammy64"
    web1.vm.hostname = "self-hosted-runner"
    web1.vm.network "private_network", ip: "192.168.137.10"

    web1.vm.provider "virtualbox" do |vb_web1|
      vb_web1.name = "self-hosted-runner"
      vb_web1.memory = 4096        # 4GB RAM
      vb_web1.cpus = 2             # 2 CPU
    end
  end
end
