Vagrant.configure("2") do |config|

  # Máy ảo self-hosted runner (ví dụ web1)
  config.vm.define "self-hosted-runner" do |web1|
    web1.vm.box = "ubuntu/jammy64"
    web1.vm.hostname = "self-hosted-runner"
    web1.vm.network "private_network", ip: "192.168.137.10"

    web1.vm.provider "virtualbox" do |vb_web1|
      vb_web1.name = "self-hosted-runner"
      vb_web1.memory = 8192        # 8GB RAM
      vb_web1.cpus = 4             # 4 CPU
    end
  end

  # Máy ảo Jenkins
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "ubuntu/jammy64"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.network "private_network", ip: "192.168.137.11"

    # Forwarded ports để expose Jenkins qua host
    jenkins.vm.network "forwarded_port", guest: 8080, host: 8080   # Jenkins port
    jenkins.vm.network "forwarded_port", guest: 80, host: 80       # HTTP cho Certbot
    jenkins.vm.network "forwarded_port", guest: 443, host: 443     # HTTPS cho Nginx SSL

    jenkins.vm.provider "virtualbox" do |vb_jenkins|
      vb_jenkins.name = "jenkins"
      vb_jenkins.memory = 1024     # 1GB RAM
      vb_jenkins.cpus = 1          # 1 CPU
    end
  end

  # # Máy ảo NFS server
  # config.vm.define "nfs-server" do |nfs|
  #   nfs.vm.box = "ubuntu/jammy64"
  #   nfs.vm.hostname = "nfs-server"
  #   nfs.vm.network "private_network", ip: "192.168.137.12"

  #   nfs.vm.provider "virtualbox" do |vb_nfs|
  #     vb_nfs.name = "nfs-server"
  #     vb_nfs.memory = 512          # 512MB RAM
  #     vb_nfs.cpus = 1              # 1 CPU
  #   end
  # end

  # # Máy ảo Monitoring (Prometheus/Grafana)
  # config.vm.define "monitoring" do |mon|
  #   mon.vm.box = "ubuntu/jammy64"
  #   mon.vm.hostname = "monitoring"
  #   mon.vm.network "private_network", ip: "192.168.137.13"

  #   mon.vm.provider "virtualbox" do |vb_mon|
  #     vb_mon.name = "monitoring"
  #     vb_mon.memory = 2048         # 2GB RAM
  #     vb_mon.cpus = 1              # 1 CPU
  #   end
  # end
end
