all:
  children:
    local:
      hosts:
        self-hosted-runner:
          ansible_host: 192.168.137.10
        jenkins:
          ansible_host: 192.168.137.11
      vars:
        ansible_user: vagrant
        ansible_ssh_private_key_file: /root/.ssh/id_rsa
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no' #bỏ qua xác thực host-key

    aws:
      hosts:
        swarm-manager: #có thể dùng EIP (~0.005 đô) => off E2 not free => open EC2 free
          ansible_host: 52.77.11.219
          # Không có ProxyJump ở đây
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    managers:
      hosts:
        swarm-manager:

    workers:           # ← ProxyJump chỉ cho workers
      hosts:
        swarm-worker1:
          ansible_host: 10.0.2.240 #private nên không cần chỉnh
        swarm-worker2:
          ansible_host: 10.0.3.42 #private nên không cần chỉnh
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        ansible_ssh_extra_args: '-o ProxyJump=ubuntu@52.77.11.219'

    swarm:
      children:
        managers:
        workers:

    nfs:
      hosts:
        nfs-server:
          ansible_host: 10.0.4.168 #private
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        ansible_ssh_extra_args: '-o ProxyJump=ubuntu@52.77.11.219'

    monitoring:
      hosts:
        monitoring-server:
          ansible_host: 10.0.5.134
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        ansible_ssh_extra_args: '-o ProxyJump=ubuntu@52.77.11.219'
